/**
 * Banco de dados local de alimentos comuns brasileiros
 *
 * Usado para evitar chamadas desnecessárias à IA quando o alimento
 * é bem conhecido e padronizado.
 */

export interface FoodItem {
  name: string;           // nome normalizado
  aliases: string[];      // variações de nome
  defaultGrams: number;   // porção padrão em gramas
  caloriesPer100g: number;
  proteinPer100g: number;
  carbsPer100g: number;
  fatPer100g: number;
  isAmbiguous: boolean;   // true = precisa perguntar tipo/variação
  ambiguousOptions?: string[]; // opções quando ambíguo
}

// Função para normalizar texto (remove acentos, lowercase)
export function normalizeText(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}

// Banco de dados de alimentos
export const FOOD_DATABASE: FoodItem[] = [
  // ==================== PROTEÍNAS ====================
  {
    name: "ovo",
    aliases: ["ovo cozido", "ovo frito", "ovo mexido", "ovos", "ovo inteiro"],
    defaultGrams: 50,
    caloriesPer100g: 143,
    proteinPer100g: 13,
    carbsPer100g: 1,
    fatPer100g: 10,
    isAmbiguous: false,
  },
  {
    name: "clara de ovo",
    aliases: ["clara", "claras"],
    defaultGrams: 33,
    caloriesPer100g: 52,
    proteinPer100g: 11,
    carbsPer100g: 1,
    fatPer100g: 0,
    isAmbiguous: false,
  },
  {
    name: "frango grelhado",
    aliases: ["peito de frango", "frango", "filé de frango", "file de frango"],
    defaultGrams: 150,
    caloriesPer100g: 165,
    proteinPer100g: 31,
    carbsPer100g: 0,
    fatPer100g: 4,
    isAmbiguous: false,
  },
  {
    name: "coxa de frango",
    aliases: ["sobrecoxa", "coxa e sobrecoxa"],
    defaultGrams: 100,
    caloriesPer100g: 209,
    proteinPer100g: 26,
    carbsPer100g: 0,
    fatPer100g: 11,
    isAmbiguous: false,
  },
  {
    name: "carne bovina",
    aliases: ["carne vermelha", "bife", "carne moída", "patinho", "alcatra", "filé mignon"],
    defaultGrams: 150,
    caloriesPer100g: 250,
    proteinPer100g: 26,
    carbsPer100g: 0,
    fatPer100g: 15,
    isAmbiguous: false,
  },
  {
    name: "carne de porco",
    aliases: ["lombo", "bisteca", "pernil"],
    defaultGrams: 150,
    caloriesPer100g: 242,
    proteinPer100g: 27,
    carbsPer100g: 0,
    fatPer100g: 14,
    isAmbiguous: false,
  },
  {
    name: "peixe",
    aliases: ["peixe grelhado", "filé de peixe", "tilápia", "merluza", "pescada"],
    defaultGrams: 150,
    caloriesPer100g: 96,
    proteinPer100g: 20,
    carbsPer100g: 0,
    fatPer100g: 2,
    isAmbiguous: false,
  },
  {
    name: "salmão",
    aliases: ["salmao", "salmão grelhado"],
    defaultGrams: 150,
    caloriesPer100g: 208,
    proteinPer100g: 20,
    carbsPer100g: 0,
    fatPer100g: 13,
    isAmbiguous: false,
  },
  {
    name: "atum",
    aliases: ["atum em lata", "atum enlatado"],
    defaultGrams: 60,
    caloriesPer100g: 116,
    proteinPer100g: 26,
    carbsPer100g: 0,
    fatPer100g: 1,
    isAmbiguous: false,
  },
  {
    name: "sardinha",
    aliases: ["sardinha em lata", "sardinha enlatada"],
    defaultGrams: 60,
    caloriesPer100g: 208,
    proteinPer100g: 25,
    carbsPer100g: 0,
    fatPer100g: 11,
    isAmbiguous: false,
  },
  {
    name: "camarão",
    aliases: ["camarao"],
    defaultGrams: 100,
    caloriesPer100g: 99,
    proteinPer100g: 24,
    carbsPer100g: 0,
    fatPer100g: 1,
    isAmbiguous: false,
  },
  {
    name: "linguiça",
    aliases: ["linguica", "linguiça calabresa", "calabresa"],
    defaultGrams: 60,
    caloriesPer100g: 296,
    proteinPer100g: 16,
    carbsPer100g: 2,
    fatPer100g: 25,
    isAmbiguous: false,
  },
  {
    name: "bacon",
    aliases: ["toucinho"],
    defaultGrams: 30,
    caloriesPer100g: 541,
    proteinPer100g: 37,
    carbsPer100g: 1,
    fatPer100g: 42,
    isAmbiguous: false,
  },
  {
    name: "presunto",
    aliases: ["presunto fatiado"],
    defaultGrams: 30,
    caloriesPer100g: 145,
    proteinPer100g: 21,
    carbsPer100g: 2,
    fatPer100g: 6,
    isAmbiguous: false,
  },
  {
    name: "peito de peru",
    aliases: ["peru defumado", "blanquet"],
    defaultGrams: 30,
    caloriesPer100g: 104,
    proteinPer100g: 17,
    carbsPer100g: 4,
    fatPer100g: 2,
    isAmbiguous: false,
  },

  // ==================== CARBOIDRATOS ====================
  {
    name: "arroz branco",
    aliases: ["arroz", "arroz cozido"],
    defaultGrams: 150,
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28,
    fatPer100g: 0.3,
    isAmbiguous: false,
  },
  {
    name: "arroz integral",
    aliases: ["arroz integral cozido"],
    defaultGrams: 150,
    caloriesPer100g: 111,
    proteinPer100g: 2.6,
    carbsPer100g: 23,
    fatPer100g: 0.9,
    isAmbiguous: false,
  },
  {
    name: "feijão",
    aliases: ["feijao", "feijão carioca", "feijão preto", "feijão cozido"],
    defaultGrams: 100,
    caloriesPer100g: 77,
    proteinPer100g: 5,
    carbsPer100g: 14,
    fatPer100g: 0.5,
    isAmbiguous: false,
  },
  {
    name: "batata",
    aliases: ["batata cozida", "batata inglesa"],
    defaultGrams: 150,
    caloriesPer100g: 77,
    proteinPer100g: 2,
    carbsPer100g: 17,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "batata doce",
    aliases: ["batata-doce"],
    defaultGrams: 150,
    caloriesPer100g: 86,
    proteinPer100g: 1.6,
    carbsPer100g: 20,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "batata frita",
    aliases: ["fritas", "french fries"],
    defaultGrams: 100,
    caloriesPer100g: 312,
    proteinPer100g: 3.4,
    carbsPer100g: 41,
    fatPer100g: 15,
    isAmbiguous: false,
  },
  {
    name: "mandioca",
    aliases: ["macaxeira", "aipim", "mandioca cozida"],
    defaultGrams: 150,
    caloriesPer100g: 125,
    proteinPer100g: 1,
    carbsPer100g: 30,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "macarrão",
    aliases: ["massa", "espaguete", "penne", "macarrao"],
    defaultGrams: 200,
    caloriesPer100g: 131,
    proteinPer100g: 5,
    carbsPer100g: 25,
    fatPer100g: 1,
    isAmbiguous: false,
  },
  {
    name: "pão",
    aliases: [],
    defaultGrams: 50,
    caloriesPer100g: 265,
    proteinPer100g: 9,
    carbsPer100g: 49,
    fatPer100g: 3,
    isAmbiguous: true,
    ambiguousOptions: ["pão francês", "pão integral", "pão de forma", "pão de queijo"],
  },
  {
    name: "pão francês",
    aliases: ["pao frances", "pãozinho", "pão de sal"],
    defaultGrams: 50,
    caloriesPer100g: 265,
    proteinPer100g: 9,
    carbsPer100g: 49,
    fatPer100g: 3,
    isAmbiguous: false,
  },
  {
    name: "pão integral",
    aliases: ["pao integral"],
    defaultGrams: 50,
    caloriesPer100g: 247,
    proteinPer100g: 13,
    carbsPer100g: 41,
    fatPer100g: 4,
    isAmbiguous: false,
  },
  {
    name: "pão de forma",
    aliases: ["pao de forma", "pão fatiado"],
    defaultGrams: 25,
    caloriesPer100g: 253,
    proteinPer100g: 8,
    carbsPer100g: 47,
    fatPer100g: 4,
    isAmbiguous: false,
  },
  {
    name: "pão de queijo",
    aliases: ["pao de queijo"],
    defaultGrams: 40,
    caloriesPer100g: 363,
    proteinPer100g: 5,
    carbsPer100g: 34,
    fatPer100g: 23,
    isAmbiguous: false,
  },
  {
    name: "tapioca",
    aliases: ["tapioca com recheio"],
    defaultGrams: 50,
    caloriesPer100g: 330,
    proteinPer100g: 0,
    carbsPer100g: 80,
    fatPer100g: 0,
    isAmbiguous: false,
  },
  {
    name: "cuscuz",
    aliases: ["cuscuz de milho"],
    defaultGrams: 150,
    caloriesPer100g: 112,
    proteinPer100g: 4,
    carbsPer100g: 25,
    fatPer100g: 0.5,
    isAmbiguous: false,
  },
  {
    name: "aveia",
    aliases: ["aveia em flocos", "flocos de aveia"],
    defaultGrams: 40,
    caloriesPer100g: 389,
    proteinPer100g: 17,
    carbsPer100g: 66,
    fatPer100g: 7,
    isAmbiguous: false,
  },
  {
    name: "granola",
    aliases: [],
    defaultGrams: 40,
    caloriesPer100g: 489,
    proteinPer100g: 10,
    carbsPer100g: 64,
    fatPer100g: 20,
    isAmbiguous: false,
  },
  {
    name: "torrada",
    aliases: ["torrada integral"],
    defaultGrams: 20,
    caloriesPer100g: 407,
    proteinPer100g: 11,
    carbsPer100g: 72,
    fatPer100g: 9,
    isAmbiguous: false,
  },
  {
    name: "milho",
    aliases: ["milho cozido", "espiga de milho"],
    defaultGrams: 100,
    caloriesPer100g: 96,
    proteinPer100g: 3.4,
    carbsPer100g: 21,
    fatPer100g: 1.4,
    isAmbiguous: false,
  },
  {
    name: "pipoca",
    aliases: ["pipoca de microondas"],
    defaultGrams: 30,
    caloriesPer100g: 387,
    proteinPer100g: 13,
    carbsPer100g: 78,
    fatPer100g: 5,
    isAmbiguous: false,
  },

  // ==================== LATICÍNIOS ====================
  {
    name: "leite",
    aliases: ["leite integral"],
    defaultGrams: 200,
    caloriesPer100g: 61,
    proteinPer100g: 3.2,
    carbsPer100g: 4.8,
    fatPer100g: 3.3,
    isAmbiguous: true,
    ambiguousOptions: ["leite integral", "leite desnatado", "leite semi-desnatado"],
  },
  {
    name: "leite integral",
    aliases: [],
    defaultGrams: 200,
    caloriesPer100g: 61,
    proteinPer100g: 3.2,
    carbsPer100g: 4.8,
    fatPer100g: 3.3,
    isAmbiguous: false,
  },
  {
    name: "leite desnatado",
    aliases: [],
    defaultGrams: 200,
    caloriesPer100g: 35,
    proteinPer100g: 3.4,
    carbsPer100g: 5,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "queijo",
    aliases: [],
    defaultGrams: 30,
    caloriesPer100g: 350,
    proteinPer100g: 23,
    carbsPer100g: 2,
    fatPer100g: 28,
    isAmbiguous: true,
    ambiguousOptions: ["queijo mussarela", "queijo prato", "queijo branco/minas", "queijo cottage"],
  },
  {
    name: "queijo mussarela",
    aliases: ["mussarela", "muçarela"],
    defaultGrams: 30,
    caloriesPer100g: 280,
    proteinPer100g: 22,
    carbsPer100g: 2,
    fatPer100g: 22,
    isAmbiguous: false,
  },
  {
    name: "queijo prato",
    aliases: [],
    defaultGrams: 30,
    caloriesPer100g: 360,
    proteinPer100g: 23,
    carbsPer100g: 0,
    fatPer100g: 29,
    isAmbiguous: false,
  },
  {
    name: "queijo minas",
    aliases: ["queijo branco", "queijo minas frescal", "queijo frescal"],
    defaultGrams: 30,
    caloriesPer100g: 264,
    proteinPer100g: 17,
    carbsPer100g: 3,
    fatPer100g: 20,
    isAmbiguous: false,
  },
  {
    name: "queijo cottage",
    aliases: ["cottage"],
    defaultGrams: 50,
    caloriesPer100g: 98,
    proteinPer100g: 11,
    carbsPer100g: 3,
    fatPer100g: 4,
    isAmbiguous: false,
  },
  {
    name: "requeijão",
    aliases: ["requeijao", "requeijão cremoso"],
    defaultGrams: 30,
    caloriesPer100g: 257,
    proteinPer100g: 7,
    carbsPer100g: 3,
    fatPer100g: 24,
    isAmbiguous: false,
  },
  {
    name: "iogurte",
    aliases: [],
    defaultGrams: 170,
    caloriesPer100g: 63,
    proteinPer100g: 5,
    carbsPer100g: 7,
    fatPer100g: 2,
    isAmbiguous: true,
    ambiguousOptions: ["iogurte natural", "iogurte grego", "iogurte com frutas"],
  },
  {
    name: "iogurte natural",
    aliases: ["iogurte natural integral"],
    defaultGrams: 170,
    caloriesPer100g: 63,
    proteinPer100g: 5,
    carbsPer100g: 7,
    fatPer100g: 2,
    isAmbiguous: false,
  },
  {
    name: "iogurte grego",
    aliases: ["grego", "iogurte proteico"],
    defaultGrams: 170,
    caloriesPer100g: 97,
    proteinPer100g: 9,
    carbsPer100g: 4,
    fatPer100g: 5,
    isAmbiguous: false,
  },
  {
    name: "manteiga",
    aliases: [],
    defaultGrams: 10,
    caloriesPer100g: 717,
    proteinPer100g: 1,
    carbsPer100g: 0,
    fatPer100g: 81,
    isAmbiguous: false,
  },
  {
    name: "creme de leite",
    aliases: [],
    defaultGrams: 30,
    caloriesPer100g: 195,
    proteinPer100g: 2,
    carbsPer100g: 4,
    fatPer100g: 19,
    isAmbiguous: false,
  },

  // ==================== VERDURAS E LEGUMES ====================
  {
    name: "alface",
    aliases: ["folha de alface"],
    defaultGrams: 50,
    caloriesPer100g: 15,
    proteinPer100g: 1.4,
    carbsPer100g: 2.9,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "tomate",
    aliases: ["tomates"],
    defaultGrams: 100,
    caloriesPer100g: 18,
    proteinPer100g: 0.9,
    carbsPer100g: 3.9,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "cebola",
    aliases: ["cebolas"],
    defaultGrams: 50,
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    carbsPer100g: 9,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "cenoura",
    aliases: ["cenouras"],
    defaultGrams: 80,
    caloriesPer100g: 41,
    proteinPer100g: 0.9,
    carbsPer100g: 10,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "brócolis",
    aliases: ["brocolis", "brócoli"],
    defaultGrams: 100,
    caloriesPer100g: 34,
    proteinPer100g: 2.8,
    carbsPer100g: 7,
    fatPer100g: 0.4,
    isAmbiguous: false,
  },
  {
    name: "couve",
    aliases: ["couve refogada", "couve manteiga"],
    defaultGrams: 50,
    caloriesPer100g: 27,
    proteinPer100g: 2.9,
    carbsPer100g: 4.4,
    fatPer100g: 0.4,
    isAmbiguous: false,
  },
  {
    name: "espinafre",
    aliases: [],
    defaultGrams: 50,
    caloriesPer100g: 23,
    proteinPer100g: 2.9,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    isAmbiguous: false,
  },
  {
    name: "abobrinha",
    aliases: [],
    defaultGrams: 100,
    caloriesPer100g: 17,
    proteinPer100g: 1.2,
    carbsPer100g: 3.1,
    fatPer100g: 0.3,
    isAmbiguous: false,
  },
  {
    name: "berinjela",
    aliases: [],
    defaultGrams: 100,
    caloriesPer100g: 25,
    proteinPer100g: 1,
    carbsPer100g: 6,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "pepino",
    aliases: [],
    defaultGrams: 100,
    caloriesPer100g: 16,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "pimentão",
    aliases: ["pimentao"],
    defaultGrams: 80,
    caloriesPer100g: 31,
    proteinPer100g: 1,
    carbsPer100g: 6,
    fatPer100g: 0.3,
    isAmbiguous: false,
  },
  {
    name: "abóbora",
    aliases: ["abobora", "abóbora cabotiá", "abóbora moranga"],
    defaultGrams: 100,
    caloriesPer100g: 26,
    proteinPer100g: 1,
    carbsPer100g: 6.5,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "chuchu",
    aliases: [],
    defaultGrams: 100,
    caloriesPer100g: 19,
    proteinPer100g: 0.8,
    carbsPer100g: 4.5,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "vagem",
    aliases: ["feijão verde"],
    defaultGrams: 80,
    caloriesPer100g: 31,
    proteinPer100g: 1.8,
    carbsPer100g: 7,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "beterraba",
    aliases: [],
    defaultGrams: 80,
    caloriesPer100g: 43,
    proteinPer100g: 1.6,
    carbsPer100g: 10,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "salada",
    aliases: ["salada verde", "salada mista"],
    defaultGrams: 100,
    caloriesPer100g: 20,
    proteinPer100g: 1.5,
    carbsPer100g: 3,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "legumes",
    aliases: ["legumes cozidos", "legumes no vapor"],
    defaultGrams: 150,
    caloriesPer100g: 35,
    proteinPer100g: 1.5,
    carbsPer100g: 7,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },

  // ==================== FRUTAS ====================
  {
    name: "banana",
    aliases: ["banana prata", "banana nanica"],
    defaultGrams: 100,
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 23,
    fatPer100g: 0.3,
    isAmbiguous: false,
  },
  {
    name: "maçã",
    aliases: ["maca"],
    defaultGrams: 150,
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 14,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "laranja",
    aliases: [],
    defaultGrams: 150,
    caloriesPer100g: 47,
    proteinPer100g: 0.9,
    carbsPer100g: 12,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "mamão",
    aliases: ["mamao", "mamão papaya"],
    defaultGrams: 150,
    caloriesPer100g: 43,
    proteinPer100g: 0.5,
    carbsPer100g: 11,
    fatPer100g: 0.3,
    isAmbiguous: false,
  },
  {
    name: "melancia",
    aliases: [],
    defaultGrams: 200,
    caloriesPer100g: 30,
    proteinPer100g: 0.6,
    carbsPer100g: 8,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "melão",
    aliases: ["melao"],
    defaultGrams: 200,
    caloriesPer100g: 34,
    proteinPer100g: 0.8,
    carbsPer100g: 8,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "abacaxi",
    aliases: [],
    defaultGrams: 150,
    caloriesPer100g: 50,
    proteinPer100g: 0.5,
    carbsPer100g: 13,
    fatPer100g: 0.1,
    isAmbiguous: false,
  },
  {
    name: "manga",
    aliases: [],
    defaultGrams: 150,
    caloriesPer100g: 60,
    proteinPer100g: 0.8,
    carbsPer100g: 15,
    fatPer100g: 0.4,
    isAmbiguous: false,
  },
  {
    name: "uva",
    aliases: ["uvas"],
    defaultGrams: 100,
    caloriesPer100g: 69,
    proteinPer100g: 0.7,
    carbsPer100g: 18,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "morango",
    aliases: ["morangos"],
    defaultGrams: 100,
    caloriesPer100g: 32,
    proteinPer100g: 0.7,
    carbsPer100g: 8,
    fatPer100g: 0.3,
    isAmbiguous: false,
  },
  {
    name: "abacate",
    aliases: [],
    defaultGrams: 100,
    caloriesPer100g: 160,
    proteinPer100g: 2,
    carbsPer100g: 9,
    fatPer100g: 15,
    isAmbiguous: false,
  },
  {
    name: "açaí",
    aliases: ["acai", "tigela de açaí"],
    defaultGrams: 200,
    caloriesPer100g: 58,
    proteinPer100g: 1,
    carbsPer100g: 6,
    fatPer100g: 3.5,
    isAmbiguous: false,
  },
  {
    name: "coco",
    aliases: ["coco ralado", "coco fresco"],
    defaultGrams: 30,
    caloriesPer100g: 354,
    proteinPer100g: 3.3,
    carbsPer100g: 15,
    fatPer100g: 33,
    isAmbiguous: false,
  },

  // ==================== OLEAGINOSAS E SEMENTES ====================
  {
    name: "amendoim",
    aliases: [],
    defaultGrams: 30,
    caloriesPer100g: 567,
    proteinPer100g: 26,
    carbsPer100g: 16,
    fatPer100g: 49,
    isAmbiguous: false,
  },
  {
    name: "castanha de caju",
    aliases: ["castanha", "caju"],
    defaultGrams: 30,
    caloriesPer100g: 553,
    proteinPer100g: 18,
    carbsPer100g: 30,
    fatPer100g: 44,
    isAmbiguous: false,
  },
  {
    name: "castanha do pará",
    aliases: ["castanha do para"],
    defaultGrams: 20,
    caloriesPer100g: 656,
    proteinPer100g: 14,
    carbsPer100g: 12,
    fatPer100g: 66,
    isAmbiguous: false,
  },
  {
    name: "nozes",
    aliases: ["noz"],
    defaultGrams: 20,
    caloriesPer100g: 654,
    proteinPer100g: 15,
    carbsPer100g: 14,
    fatPer100g: 65,
    isAmbiguous: false,
  },
  {
    name: "amêndoas",
    aliases: ["amendoas", "amêndoa"],
    defaultGrams: 30,
    caloriesPer100g: 579,
    proteinPer100g: 21,
    carbsPer100g: 22,
    fatPer100g: 50,
    isAmbiguous: false,
  },
  {
    name: "pasta de amendoim",
    aliases: ["manteiga de amendoim"],
    defaultGrams: 30,
    caloriesPer100g: 588,
    proteinPer100g: 25,
    carbsPer100g: 20,
    fatPer100g: 50,
    isAmbiguous: false,
  },
  {
    name: "chia",
    aliases: ["semente de chia"],
    defaultGrams: 15,
    caloriesPer100g: 486,
    proteinPer100g: 17,
    carbsPer100g: 42,
    fatPer100g: 31,
    isAmbiguous: false,
  },
  {
    name: "linhaça",
    aliases: ["semente de linhaça"],
    defaultGrams: 15,
    caloriesPer100g: 534,
    proteinPer100g: 18,
    carbsPer100g: 29,
    fatPer100g: 42,
    isAmbiguous: false,
  },

  // ==================== BEBIDAS ====================
  {
    name: "café",
    aliases: ["cafe", "café preto", "cafezinho"],
    defaultGrams: 50,
    caloriesPer100g: 2,
    proteinPer100g: 0.1,
    carbsPer100g: 0,
    fatPer100g: 0,
    isAmbiguous: false,
  },
  {
    name: "café com leite",
    aliases: ["cafe com leite"],
    defaultGrams: 200,
    caloriesPer100g: 40,
    proteinPer100g: 2,
    carbsPer100g: 4,
    fatPer100g: 2,
    isAmbiguous: false,
  },
  {
    name: "suco de laranja",
    aliases: ["suco natural de laranja"],
    defaultGrams: 250,
    caloriesPer100g: 45,
    proteinPer100g: 0.7,
    carbsPer100g: 10,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "água de coco",
    aliases: ["agua de coco"],
    defaultGrams: 250,
    caloriesPer100g: 19,
    proteinPer100g: 0.7,
    carbsPer100g: 4,
    fatPer100g: 0.2,
    isAmbiguous: false,
  },
  {
    name: "refrigerante",
    aliases: ["coca-cola", "refrigerante de cola"],
    defaultGrams: 350,
    caloriesPer100g: 42,
    proteinPer100g: 0,
    carbsPer100g: 11,
    fatPer100g: 0,
    isAmbiguous: false,
  },
  {
    name: "cerveja",
    aliases: [],
    defaultGrams: 350,
    caloriesPer100g: 43,
    proteinPer100g: 0.5,
    carbsPer100g: 3.6,
    fatPer100g: 0,
    isAmbiguous: false,
  },
  {
    name: "whey protein",
    aliases: ["whey", "proteína whey", "shake de whey"],
    defaultGrams: 30,
    caloriesPer100g: 400,
    proteinPer100g: 80,
    carbsPer100g: 7,
    fatPer100g: 6,
    isAmbiguous: false,
  },

  // ==================== OUTROS ====================
  {
    name: "azeite",
    aliases: ["azeite de oliva", "azeite extra virgem"],
    defaultGrams: 15,
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    isAmbiguous: false,
  },
  {
    name: "óleo",
    aliases: ["oleo", "óleo de soja", "óleo vegetal"],
    defaultGrams: 15,
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    isAmbiguous: false,
  },
  {
    name: "mel",
    aliases: [],
    defaultGrams: 20,
    caloriesPer100g: 304,
    proteinPer100g: 0.3,
    carbsPer100g: 82,
    fatPer100g: 0,
    isAmbiguous: false,
  },
  {
    name: "açúcar",
    aliases: ["acucar", "açúcar refinado"],
    defaultGrams: 10,
    caloriesPer100g: 387,
    proteinPer100g: 0,
    carbsPer100g: 100,
    fatPer100g: 0,
    isAmbiguous: false,
  },
  {
    name: "chocolate",
    aliases: ["chocolate ao leite", "barra de chocolate"],
    defaultGrams: 30,
    caloriesPer100g: 535,
    proteinPer100g: 7,
    carbsPer100g: 60,
    fatPer100g: 30,
    isAmbiguous: false,
  },
  {
    name: "sorvete",
    aliases: ["sorvete de massa"],
    defaultGrams: 100,
    caloriesPer100g: 207,
    proteinPer100g: 3.5,
    carbsPer100g: 24,
    fatPer100g: 11,
    isAmbiguous: false,
  },
  {
    name: "bolo",
    aliases: ["bolo de chocolate", "bolo simples"],
    defaultGrams: 100,
    caloriesPer100g: 367,
    proteinPer100g: 5,
    carbsPer100g: 51,
    fatPer100g: 16,
    isAmbiguous: false,
  },
  {
    name: "biscoito",
    aliases: ["bolacha", "biscoito cream cracker"],
    defaultGrams: 30,
    caloriesPer100g: 433,
    proteinPer100g: 9,
    carbsPer100g: 67,
    fatPer100g: 15,
    isAmbiguous: false,
  },
  {
    name: "pizza",
    aliases: ["fatia de pizza"],
    defaultGrams: 100,
    caloriesPer100g: 266,
    proteinPer100g: 11,
    carbsPer100g: 33,
    fatPer100g: 10,
    isAmbiguous: false,
  },
  {
    name: "hambúrguer",
    aliases: ["hamburguer", "burger", "sanduíche de hambúrguer"],
    defaultGrams: 200,
    caloriesPer100g: 254,
    proteinPer100g: 13,
    carbsPer100g: 24,
    fatPer100g: 12,
    isAmbiguous: false,
  },
  {
    name: "hot dog",
    aliases: ["cachorro quente"],
    defaultGrams: 150,
    caloriesPer100g: 247,
    proteinPer100g: 10,
    carbsPer100g: 18,
    fatPer100g: 15,
    isAmbiguous: false,
  },
  {
    name: "coxinha",
    aliases: [],
    defaultGrams: 80,
    caloriesPer100g: 263,
    proteinPer100g: 10,
    carbsPer100g: 25,
    fatPer100g: 14,
    isAmbiguous: false,
  },
  {
    name: "pastel",
    aliases: ["pastel de carne", "pastel de queijo"],
    defaultGrams: 80,
    caloriesPer100g: 289,
    proteinPer100g: 6,
    carbsPer100g: 26,
    fatPer100g: 18,
    isAmbiguous: false,
  },
  {
    name: "empada",
    aliases: ["empadinha"],
    defaultGrams: 60,
    caloriesPer100g: 350,
    proteinPer100g: 7,
    carbsPer100g: 25,
    fatPer100g: 25,
    isAmbiguous: false,
  },
];

/**
 * Busca um alimento no banco de dados
 * @param searchTerm Termo de busca (nome ou alias)
 * @returns FoodItem ou null se não encontrado
 */
export function findFood(searchTerm: string): FoodItem | null {
  const normalized = normalizeText(searchTerm);

  // Busca exata no nome
  const exactMatch = FOOD_DATABASE.find(
    (food) => normalizeText(food.name) === normalized
  );
  if (exactMatch) return exactMatch;

  // Busca nos aliases
  const aliasMatch = FOOD_DATABASE.find((food) =>
    food.aliases.some((alias) => normalizeText(alias) === normalized)
  );
  if (aliasMatch) return aliasMatch;

  // Busca parcial (contém o termo)
  const partialMatch = FOOD_DATABASE.find(
    (food) =>
      normalizeText(food.name).includes(normalized) ||
      food.aliases.some((alias) => normalizeText(alias).includes(normalized))
  );
  if (partialMatch) return partialMatch;

  // Busca reversa (termo contém o nome do alimento)
  const reverseMatch = FOOD_DATABASE.find(
    (food) =>
      normalized.includes(normalizeText(food.name)) ||
      food.aliases.some((alias) => normalized.includes(normalizeText(alias)))
  );

  return reverseMatch || null;
}

/**
 * Calcula informações nutricionais baseado na gramatura
 */
export function calculateNutrition(food: FoodItem, grams: number) {
  const multiplier = grams / 100;
  return {
    name: food.name,
    grams,
    calories: Math.round(food.caloriesPer100g * multiplier),
    protein: Math.round(food.proteinPer100g * multiplier * 10) / 10,
    carbs: Math.round(food.carbsPer100g * multiplier * 10) / 10,
    fat: Math.round(food.fatPer100g * multiplier * 10) / 10,
  };
}

/**
 * Retorna todos os alimentos que contêm o termo de busca
 */
export function searchFoods(searchTerm: string): FoodItem[] {
  const normalized = normalizeText(searchTerm);

  return FOOD_DATABASE.filter(
    (food) =>
      normalizeText(food.name).includes(normalized) ||
      food.aliases.some((alias) => normalizeText(alias).includes(normalized))
  );
}
